export type GrammarTopic = {
  id: string;
  group: string;
  title: string;
  easy: string;
  rule: string;
  examples: string[];
  commonMistake?: string;
};

export const grammarGroups = [
  "Sentence Basics",
  "Parts of Speech",
  "Tenses",
  "Verbs & Agreement",
  "Questions & Modals",
  "Building Sentences",
  "Advanced Grammar",
  "Writing Rules",
] as const;

export const grammarTopics: GrammarTopic[] = [
  {
    id: "sentence-structure",
    group: "Sentence Basics",
    title: "Sentence Structure",
    easy: "A normal English sentence usually needs a subject and a verb. The subject tells us who or what; the verb tells us the action or state.",
    rule: "Basic pattern: Subject + Verb + Object/Complement.",
    examples: ["I study English.", "She is confident.", "They built a website."],
    commonMistake: "Wrong: Is a good student. → Right: He is a good student.",
  },
  {
    id: "sentence-types",
    group: "Sentence Basics",
    title: "Types of Sentences",
    easy: "Sentences can make a statement, ask a question, give a command, or show strong feeling.",
    rule: "Declarative, Interrogative, Imperative, Exclamatory.",
    examples: ["I enjoy programming.", "Do you enjoy programming?", "Open the file.", "What a great idea!"],
  },
  {
    id: "simple-compound-complex",
    group: "Sentence Basics",
    title: "Simple, Compound & Complex Sentences",
    easy: "A simple sentence has one main idea. A compound sentence joins two main ideas. A complex sentence has a main idea plus a dependent idea.",
    rule: "Simple = 1 independent clause. Compound = 2+ independent clauses. Complex = independent + dependent clause.",
    examples: ["I study CSE.", "I study CSE, and I practice English.", "I practice English because I want to present confidently."],
  },
  {
    id: "parts-of-speech",
    group: "Parts of Speech",
    title: "8 Parts of Speech",
    easy: "Every word has a job. The main jobs are noun, pronoun, verb, adjective, adverb, preposition, conjunction, and interjection.",
    rule: "Learn the job of the word inside the sentence, not only its dictionary meaning.",
    examples: ["developer = noun", "build = verb", "efficient = adjective", "carefully = adverb"],
  },
  {
    id: "nouns",
    group: "Parts of Speech",
    title: "Nouns",
    easy: "A noun names a person, place, thing, idea, subject, or concept.",
    rule: "Common/proper, countable/uncountable, singular/plural, concrete/abstract.",
    examples: ["student", "Dhaka", "database", "information", "confidence"],
    commonMistake: "Information is uncountable: 'some information', not 'informations'.",
  },
  {
    id: "pronouns",
    group: "Parts of Speech",
    title: "Pronouns",
    easy: "Pronouns replace nouns so we do not repeat the same name again and again.",
    rule: "Subject: I/he/she/we/they. Object: me/him/her/us/them. Possessive: mine/his/hers/ours/theirs.",
    examples: ["Shabbir studies CSE. He enjoys it.", "Give the file to me.", "This laptop is mine."],
  },
  {
    id: "articles",
    group: "Parts of Speech",
    title: "Articles: a, an, the",
    easy: "Use a/an when something is not specific or mentioned for the first time. Use the when both people know which thing you mean.",
    rule: "a + consonant sound, an + vowel sound, the + specific/known noun.",
    examples: ["I bought a laptop.", "She is an engineer.", "The laptop is on my desk."],
    commonMistake: "Use sound, not spelling: 'an hour', but 'a university'.",
  },
  {
    id: "adjectives-adverbs",
    group: "Parts of Speech",
    title: "Adjectives & Adverbs",
    easy: "Adjectives describe nouns. Adverbs usually describe verbs, adjectives, or other adverbs.",
    rule: "Adjective: a clear explanation. Adverb: explain clearly.",
    examples: ["She gave a clear presentation.", "She presented clearly.", "The system is extremely fast."],
  },
  {
    id: "prepositions",
    group: "Parts of Speech",
    title: "Prepositions",
    easy: "Prepositions show relationships such as time, place, direction, and connection.",
    rule: "Common ones: in, on, at, to, from, for, with, by, about, between, among.",
    examples: ["at 5 PM", "on Monday", "in August", "interested in AI", "responsible for testing"],
  },
  {
    id: "present-simple",
    group: "Tenses",
    title: "Present Simple",
    easy: "Use it for habits, routines, facts, and things that are generally true.",
    rule: "I/you/we/they + base verb; he/she/it + verb-s/es.",
    examples: ["I practice English every day.", "She works in finance.", "Water boils at 100°C."],
    commonMistake: "He work → He works.",
  },
  {
    id: "present-continuous",
    group: "Tenses",
    title: "Present Continuous",
    easy: "Use it for something happening now or around now, and sometimes for temporary situations.",
    rule: "am/is/are + verb-ing.",
    examples: ["I am studying now.", "They are building a new app.", "She is preparing for IELTS this month."],
  },
  {
    id: "present-perfect",
    group: "Tenses",
    title: "Present Perfect",
    easy: "Use it when a past action is connected to now, or when the exact past time is not important.",
    rule: "have/has + past participle (V3).",
    examples: ["I have finished the task.", "She has visited London twice.", "We have learned several new words."],
    commonMistake: "Do not normally use it with a finished past time: 'I finished it yesterday', not 'I have finished it yesterday'.",
  },
  {
    id: "present-perfect-continuous",
    group: "Tenses",
    title: "Present Perfect Continuous",
    easy: "Use it for an activity that started in the past and is still continuing, or has just stopped with a visible result.",
    rule: "have/has been + verb-ing.",
    examples: ["I have been studying for two hours.", "She has been working here since 2025."],
  },
  {
    id: "past-simple",
    group: "Tenses",
    title: "Past Simple",
    easy: "Use it for a finished action at a finished time in the past.",
    rule: "verb V2; negative/question use did + base verb.",
    examples: ["I joined the course last week.", "Did you call the client?", "We did not finish the report."],
  },
  {
    id: "past-continuous",
    group: "Tenses",
    title: "Past Continuous",
    easy: "Use it for an action that was in progress at a particular moment in the past.",
    rule: "was/were + verb-ing.",
    examples: ["I was studying at 9 PM.", "They were discussing the project when I arrived."],
  },
  {
    id: "past-perfect",
    group: "Tenses",
    title: "Past Perfect",
    easy: "Use it when one past action happened before another past action.",
    rule: "had + past participle (V3).",
    examples: ["The meeting had started before I arrived.", "She had completed the report by noon."],
  },
  {
    id: "past-perfect-continuous",
    group: "Tenses",
    title: "Past Perfect Continuous",
    easy: "Use it to show how long an activity had been continuing before another past point.",
    rule: "had been + verb-ing.",
    examples: ["I had been waiting for an hour before the bus came."],
  },
  {
    id: "future-simple",
    group: "Tenses",
    title: "Future Simple",
    easy: "Use will for predictions, instant decisions, promises, and future facts.",
    rule: "will + base verb.",
    examples: ["I will call you later.", "The exam will start at 10.", "I think AI will change education."],
  },
  {
    id: "future-continuous",
    group: "Tenses",
    title: "Future Continuous",
    easy: "Use it for an action that will be in progress at a future time.",
    rule: "will be + verb-ing.",
    examples: ["This time tomorrow, I will be taking my exam."],
  },
  {
    id: "future-perfect",
    group: "Tenses",
    title: "Future Perfect",
    easy: "Use it for something that will be completed before a future deadline or point.",
    rule: "will have + past participle.",
    examples: ["By Friday, I will have finished the project."],
  },
  {
    id: "future-perfect-continuous",
    group: "Tenses",
    title: "Future Perfect Continuous",
    easy: "Use it to emphasize how long an activity will have continued by a future time.",
    rule: "will have been + verb-ing.",
    examples: ["By December, I will have been studying CSE for four months."],
  },
  {
    id: "subject-verb-agreement",
    group: "Verbs & Agreement",
    title: "Subject–Verb Agreement",
    easy: "The verb must match the subject. Singular subjects usually take singular verb forms; plural subjects take plural forms.",
    rule: "He works. They work. The list is ready. The students are ready.",
    examples: ["My friend lives in Dhaka.", "My friends live in Dhaka."],
  },
  {
    id: "regular-irregular-verbs",
    group: "Verbs & Agreement",
    title: "Regular & Irregular Verbs",
    easy: "Regular verbs usually add -ed in the past. Irregular verbs change differently and need to be learned in groups.",
    rule: "work-worked-worked; go-went-gone; write-wrote-written.",
    examples: ["I worked yesterday.", "She went home.", "He has written the email."],
  },
  {
    id: "modal-verbs",
    group: "Questions & Modals",
    title: "Modal Verbs",
    easy: "Modals add meanings like ability, possibility, advice, permission, or obligation.",
    rule: "can, could, may, might, must, should, would + base verb.",
    examples: ["I can explain it.", "You should practice daily.", "We must submit the report today."],
  },
  {
    id: "questions",
    group: "Questions & Modals",
    title: "Making Questions",
    easy: "Most questions need an auxiliary verb before the subject.",
    rule: "Do/Does/Did + subject + base verb? Be + subject...? Have/Has + subject + V3?",
    examples: ["Do you study CSE?", "Where does she work?", "Have you finished?", "Are they ready?"],
  },
  {
    id: "negatives",
    group: "Questions & Modals",
    title: "Negative Sentences",
    easy: "Use not with an auxiliary verb. If there is no auxiliary in present/past simple, use do/does/did.",
    rule: "do not, does not, did not, is not, have not, will not, cannot.",
    examples: ["I do not agree.", "She does not work here.", "They have not finished."],
  },
  {
    id: "conjunctions",
    group: "Building Sentences",
    title: "Conjunctions & Linking Words",
    easy: "These words connect ideas and make your English more natural and organized.",
    rule: "and, but, so, because, although, however, therefore, while, whereas, moreover.",
    examples: ["I was tired, but I finished the task.", "Although the task was difficult, I completed it."],
  },
  {
    id: "gerund-infinitive",
    group: "Building Sentences",
    title: "Gerunds & Infinitives",
    easy: "Some verbs are followed by -ing, some by to + verb, and some can use both with a meaning change.",
    rule: "enjoy doing; want to do; stop doing vs stop to do.",
    examples: ["I enjoy learning English.", "I want to improve my speaking."],
  },
  {
    id: "comparatives-superlatives",
    group: "Building Sentences",
    title: "Comparatives & Superlatives",
    easy: "Use comparatives to compare two things and superlatives for the highest/lowest in a group.",
    rule: "faster / more useful; fastest / most useful.",
    examples: ["Python is easier for beginners than C++.", "This is the most useful feature."],
  },
  {
    id: "conditionals",
    group: "Advanced Grammar",
    title: "Conditionals: 0, 1, 2, 3 & Mixed",
    easy: "Conditionals talk about results depending on conditions: facts, real possibilities, imaginary situations, and unreal past situations.",
    rule: "0: if + present, present. 1: if + present, will. 2: if + past, would. 3: if + had V3, would have V3.",
    examples: ["If you heat ice, it melts.", "If I study, I will improve.", "If I had more time, I would practice more.", "If I had studied, I would have passed."],
  },
  {
    id: "passive-voice",
    group: "Advanced Grammar",
    title: "Active & Passive Voice",
    easy: "Active focuses on the doer. Passive focuses on the action or result when the doer is unknown, obvious, or less important.",
    rule: "Passive = be + past participle.",
    examples: ["Active: The team built the app.", "Passive: The app was built by the team."],
  },
  {
    id: "reported-speech",
    group: "Advanced Grammar",
    title: "Reported Speech",
    easy: "Reported speech tells someone what another person said without repeating the exact quotation.",
    rule: "Pronouns, time words, and often tense forms change when reporting past speech.",
    examples: ["Direct: She said, 'I am busy.'", "Reported: She said that she was busy."],
  },
  {
    id: "relative-clauses",
    group: "Advanced Grammar",
    title: "Relative Clauses",
    easy: "Relative clauses add information about a person, thing, place, or time.",
    rule: "who = people, which = things, that = people/things, where = place, whose = possession.",
    examples: ["The student who won the contest studies CSE.", "This is the laptop that I bought."],
  },
  {
    id: "clauses-phrases",
    group: "Advanced Grammar",
    title: "Phrases & Clauses",
    easy: "A phrase is a group of words without a full subject-verb idea. A clause contains a subject and a verb.",
    rule: "Independent clauses can stand alone; dependent clauses cannot.",
    examples: ["after the meeting = phrase", "because the meeting ended = dependent clause", "We went home = independent clause"],
  },
  {
    id: "word-order",
    group: "Writing Rules",
    title: "Word Order",
    easy: "English word order is important. Moving words randomly can make a sentence sound wrong even when every word is correct.",
    rule: "Common order: Subject + Verb + Object + Place + Time.",
    examples: ["I met my teacher at university yesterday.", "She speaks English very confidently."],
  },
  {
    id: "punctuation",
    group: "Writing Rules",
    title: "Punctuation & Capitalization",
    easy: "Punctuation helps the reader understand where ideas start, stop, connect, or need emphasis.",
    rule: "Use capital letters, full stops, commas, apostrophes, question marks, colons, semicolons, and quotation marks correctly.",
    examples: ["However, I disagree.", "It's a useful feature.", "The question is: what should we do next?"],
  },
  {
    id: "common-errors",
    group: "Writing Rules",
    title: "Common Grammar Errors",
    easy: "This section focuses on mistakes learners make often, so you can fix them quickly instead of memorizing more theory.",
    rule: "Check tense, subject-verb agreement, articles, prepositions, word order, singular/plural, and sentence completeness.",
    examples: ["Wrong: I am agree. → Right: I agree.", "Wrong: He don't know. → Right: He doesn't know.", "Wrong: Discuss about it. → Right: Discuss it."],
  },
];
